// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/douyin/feed": {
            "get": {
                "description": "这个接口，在用户刚进入抖音之后就会被调用，并将视频以及作者的信息推送给用户",
                "tags": [
                    "视频相关接口"
                ],
                "summary": "获取视频流",
                "parameters": [
                    {
                        "type": "string",
                        "description": "可选参数，限制返回视频的最新投稿时间戳，精确到秒，不填表示当前时间",
                        "name": "LatestTime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "该参数只有在用户登录状态下进行设置",
                        "name": "Token",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/publish/list": {
            "get": {
                "description": "这个接口，会根据用户id去查询该用户发布的所有的视频",
                "tags": [
                    "视频相关接口"
                ],
                "summary": "获取某一用户的所发布的搜游视频",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户的userid",
                        "name": "userid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "该参数只有在用户登录状态下进行设置",
                        "name": "Token",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/swaggereget": {
            "get": {
                "description": "GET请求的例子描述",
                "tags": [
                    "Swagger请求示例"
                ],
                "summary": "GET请求的例子",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/swaggerpost": {
            "post": {
                "description": "POST请求的例子描述",
                "tags": [
                    "Swagger请求示例"
                ],
                "summary": "POST请求的例子",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "简易版抖音",
	Description:      "简易版抖音开发接口文档目录",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
