# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: './go/go.mod'

      - name: Build
        run: cd ./go && go build -o ./target -v SkyLine

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: target
          path: ./go/
